on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy website to server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Generate API Documentation
        run: composer build

      - name: Build and deploy
        uses: jenshaase/deploy-zola-via-lftp-action@main
        with:
          ftp_host: ${{ secrets.ftp_host }}
          ftp_username: ${{ secrets.ftp_username }}
          ftp_password: ${{ secrets.ftp_password }}
          remote_target_dir: ${{ secrets.ftp_remote_target_dir }}
